login:
    path:     /login
    defaults: {_controller: BlogBundle:User:login}

login_check:
    path:     /login_check

logout:
    path:   /logout

blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Default:index }

blog_add_tag:
    path:     /tags/add
    defaults: { _controller: BlogBundle:Tag:add}

blog_edit_tag:
    path:     /tags/edit/{id}
    defaults: { _controller: BlogBundle:Tag:edit}

blog_index_tag:
    path:     /tags
    defaults: { _controller: BlogBundle:Tag:index}

blog_delete_tag:
    path:     /tags/delete/{id}
    defaults: { _controller: BlogBundle:Tag:delete}

blog_index_categoria:
    path:     /categorias
    defaults: { _controller: BlogBundle:Category:index}

blog_add_categoria:
    path:     /categorias/add
    defaults: { _controller: BlogBundle:Category:add}

blog_edit_categoria:
    path:     /categorias/edit/{id}
    defaults: { _controller: BlogBundle:Category:edit}

blog_delete_categoria:
    path:     /catgegorias/delete/{id}
    defaults: { _controller: BlogBundle:Category:delete}


