BlogBundle\Entity\Tag:
      properties:
          name:
              - NotBlank: {message: "El título no puede estar vacío"}
              - Length:
                 min: 2
                 minMessage: "El nombre tiene que tener más de 2 carácteres"