BlogBundle\Entity\Tag:
    type: entity
    table: tags
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        description:
            type: text
            nullable: false
            length: 65535
            options:
                fixed: false

    oneToMany:
        entryTag:
            targetEntity: BlogBundle\Entity\EntryTag
            mappedBy: tag
            cascade:  ["persist"]
    lifecycleCallbacks: {  }
